// Wesley Memory Layer — Public API
export * from './types'
export * from './manager'
export { extractAndPersistMemories } from './extractor'
export { embedMemory, embedMemoryBatch, backfillMemoryEmbeddings } from './embedder'
export { analyzeQuery } from './query-analyzer'
export { retrieveMemories } from './retriever'
export { assembleMemoryContext, buildMemoryAttribution } from './context-assembler'
export { extractArguments, persistArguments, updateArgumentOutcome, getArgumentPatterns } from './argument-tracker'
export { detectFirmPatterns, getFirmPatterns, getFirmDashboard } from './firm-intelligence'
export { applyMemoryDecay, reinforceMemory, reinforceMemories, processFeedback, getStaleMemories, archiveStaleMemories, promoteToFirmPatterns } from './learning-loop'
export { detectPreferences, detectAndPersistPreferences, confirmPreference, dismissPreference } from './preference-detector'
export { summarizeSession } from './session-summarizer'
export { storeClausePattern, getTopClausePatterns, processDocumentClauses } from './clause-intelligence'
